# Generated by Django 5.2.6 on 2025-09-16 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
        ('schools', '0001_initial'),
        ('users', '0002_alter_user_options_user_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelblock',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AlterField(
            model_name='hostelblock',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='hostelblock',
            unique_together={('school', 'name')},
        ),
        migrations.AddIndex(
            model_name='hostelallocation',
            index=models.Index(fields=['student', 'status'], name='hostel_host_student_c7fc3e_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelallocation',
            index=models.Index(fields=['room', 'status'], name='hostel_host_room_id_3dcd2b_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelallocation',
            index=models.Index(fields=['allocation_date', 'status'], name='hostel_host_allocat_596d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelblock',
            index=models.Index(fields=['school', 'name'], name='hostel_host_school__0dbb51_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelcomplaint',
            index=models.Index(fields=['student', 'status'], name='hostel_host_student_65757f_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelcomplaint',
            index=models.Index(fields=['room', 'priority'], name='hostel_host_room_id_3e68ca_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelcomplaint',
            index=models.Index(fields=['submitted_date', 'status'], name='hostel_host_submitt_3b1f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelroom',
            index=models.Index(fields=['block', 'room_number'], name='hostel_host_block_i_5264cb_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelroom',
            index=models.Index(fields=['block', 'is_available'], name='hostel_host_block_i_1e42cb_idx'),
        ),
    ]
