# Generated by Django 5.2.6 on 2025-09-16 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['school', 'priority'], name='notificatio_school__464963_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['school', 'publish_date'], name='notificatio_school__2f3a71_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['school', 'is_active'], name='notificatio_school__5d1fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_ce6926_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['notice', 'is_read'], name='notificatio_notice__d2e43b_idx'),
        ),
    ]
