# Generated by Django 5.2.6 on 2025-09-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('block', models.CharField(db_index=True, max_length=100)),
                ('village', models.CharField(db_index=True, max_length=200)),
                ('school_name', models.CharField(max_length=300)),
                ('school_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['district', 'block', 'school_name'],
                'indexes': [models.Index(fields=['district', 'block'], name='schools_sch_distric_bade8f_idx'), models.Index(fields=['school_code', 'is_active'], name='schools_sch_school__7a24cf_idx')],
            },
        ),
    ]
