# Generated by Django 5.2.6 on 2025-09-16 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddIndex(
            model_name='admissionapplication',
            index=models.Index(fields=['school', 'status'], name='admissions__school__764290_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionapplication',
            index=models.Index(fields=['school', 'application_date'], name='admissions__school__f50e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionapplication',
            index=models.Index(fields=['course_applied', 'status'], name='admissions__course__c6e0a9_idx'),
        ),
    ]
