# Generated by Django 5.2.5 on 2025-09-16 21:13

import admissions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_admissionapplication_school_and_more'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='admissionapplication',
            name='admissions__school__764290_idx',
        ),
        migrations.RemoveIndex(
            model_name='admissionapplication',
            name='admissions__school__f50e2e_idx',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='school',
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='first_preference_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_preference_applications', to='schools.school'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='reference_id',
            field=models.CharField(db_index=True, default=admissions.models.generate_reference_id, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='second_preference_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_preference_applications', to='schools.school'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='third_preference_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_preference_applications', to='schools.school'),
        ),
        migrations.AddIndex(
            model_name='admissionapplication',
            index=models.Index(fields=['reference_id'], name='admissions__referen_7f57ac_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionapplication',
            index=models.Index(fields=['first_preference_school', 'status'], name='admissions__first_p_64521a_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionapplication',
            index=models.Index(fields=['first_preference_school', 'application_date'], name='admissions__first_p_ae82e8_idx'),
        ),
    ]
