# Generated by Django 5.2.5 on 2025-09-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_remove_admissionapplication_admissions__school__764290_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionapplication',
            name='reference_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
    ]
