# Generated by Django 5.2.5 on 2025-09-16 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_emailverification_and_more'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAdmissionDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_order', models.CharField(choices=[('1st', 'First'), ('2nd', 'Second'), ('3rd', 'Third')], max_length=10)),
                ('decision', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='pending', max_length=20)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True)),
                ('is_student_choice', models.BooleanField(default=False)),
                ('student_choice_date', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_decisions', to='admissions.admissionapplication')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_admission_decisions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_decisions', to='schools.school')),
            ],
            options={
                'ordering': ['preference_order', '-decision_date'],
                'indexes': [models.Index(fields=['school', 'decision'], name='admissions__school__39bf09_idx'), models.Index(fields=['application', 'decision'], name='admissions__applica_8b16e1_idx'), models.Index(fields=['decision', 'decision_date'], name='admissions__decisio_baf15d_idx')],
                'unique_together': {('application', 'school')},
            },
        ),
    ]
