# Generated by Django 5.2.6 on 2025-09-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_schooladmissiondecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('sc', 'SC (Scheduled Caste)'), ('st', 'ST (Scheduled Tribe)'), ('obc', 'OBC (Other Backward Class)'), ('sbc', 'SBC (Special Backward Class)')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_range', models.CharField(choices=[('1-8', 'Class 1-8'), ('9-10', 'Class 9-10'), ('11-12', 'Class 11-12')], max_length=10)),
                ('category', models.CharField(choices=[('general', 'General'), ('sc_st_obc_sbc', 'SC/ST/OBC/SBC')], max_length=20)),
                ('annual_fee_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_fee_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['class_range', 'category'],
                'unique_together': {('class_range', 'category')},
            },
        ),
    ]
