# Generated by Django 5.2.6 on 2025-09-17 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_admissionapplication_category_feestructure'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladmissiondecision',
            name='enrollment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schooladmissiondecision',
            name='enrollment_status',
            field=models.CharField(choices=[('not_enrolled', 'Not Enrolled'), ('enrolled', 'Enrolled'), ('withdrawn', 'Withdrawn')], default='not_enrolled', max_length=20),
        ),
        migrations.AddField(
            model_name='schooladmissiondecision',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schooladmissiondecision',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Payment Pending'), ('completed', 'Payment Completed'), ('failed', 'Payment Failed'), ('waived', 'Payment Waived')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='schooladmissiondecision',
            name='withdrawal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schooladmissiondecision',
            name='withdrawal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='schooladmissiondecision',
            index=models.Index(fields=['enrollment_status', 'enrollment_date'], name='admissions__enrollm_18a448_idx'),
        ),
        migrations.AddIndex(
            model_name='schooladmissiondecision',
            index=models.Index(fields=['application', 'enrollment_status'], name='admissions__applica_49cf93_idx'),
        ),
    ]
