// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cflyjkceipvywtcrhazt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmbHlqa2NlaXB2eXd0Y3JoYXp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMTMwNDQsImV4cCI6MjA3Mjg4OTA0NH0.2aiFHWM98EV-9qS_yhpCSGs0Wl4NeAO0-djoazqbJQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});