# Generated by Django 5.2.6 on 2025-09-16 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('schools', '0001_initial'),
        ('users', '0002_alter_user_options_user_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['school', 'course', 'semester'], name='exams_exam_school__dddeed_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['school', 'date'], name='exams_exam_school__dfa040_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam', 'student'], name='exams_examr_exam_id_b70e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['grade', 'entered_at'], name='exams_examr_grade_b051e0_idx'),
        ),
    ]
