# Generated by Django 5.2.6 on 2025-09-16 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('schools', '0001_initial'),
        ('users', '0002_alter_user_options_user_school_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classsession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classsession',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AlterUniqueTogether(
            name='classsession',
            unique_together={('school', 'course', 'subject', 'batch', 'date', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['session', 'student'], name='attendance__session_b22fcb_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['status', 'marked_at'], name='attendance__status_1eba77_idx'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['school', 'date'], name='attendance__school__ca611b_idx'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['school', 'course', 'subject'], name='attendance__school__07b730_idx'),
        ),
    ]
