# Generated by Django 5.2.6 on 2025-09-16 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
        ('schools', '0001_initial'),
        ('users', '0002_alter_user_options_user_school_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AlterField(
            model_name='feeinvoice',
            name='invoice_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('school', 'course', 'semester')},
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['student', 'status'], name='fees_feeinv_student_c0e8b6_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['due_date', 'status'], name='fees_feeinv_due_dat_5e3a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['fee_structure', 'student'], name='fees_feeinv_fee_str_17bea9_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['school', 'course'], name='fees_feestr_school__4ffd17_idx'),
        ),
    ]
