# Generated by Django 5.2.6 on 2025-09-16 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentprofile_first_name_studentprofile_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentprofile',
            name='children',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='is_primary_contact',
            field=models.BooleanField(default=False, help_text='Primary contact for school communications'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='relationship',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('warden', 'Warden'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='parentprofile',
            index=models.Index(fields=['student', 'is_primary_contact'], name='users_paren_student_750ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='parentprofile',
            index=models.Index(fields=['phone_number'], name='users_paren_phone_n_df306a_idx'),
        ),
    ]
