# Generated by Django 5.2.5 on 2025-09-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_parentprofile_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('warden', 'Warden'), ('admin', 'Admin'), ('management', 'Management')], max_length=20),
        ),
    ]
